name: Validate OpenAPI Spec

on:
  push:
    paths:
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yaml'

jobs:
  validate-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Validate OpenAPI Spec
        run: | 
            redocly lint ./open_api/json_api.yaml
            redocly lint ./open_api/json_api_v2.yaml

      - name: Check Validation Result
        if: failure()
        run: exit 1
